platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target 'ios-objc-flickr-api' do

  # Pods for ios-objc-flickr-api
  pod 'AFNetworking', '3.1.0'
  pod 'Mantle', '2.1.0'
  pod 'SVProgressHUD', '2.2.2'
  pod 'SDWebImage', '4.1.2'
  pod 'Reachability', '3.2'

  target 'ios-objc-flickr-apiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
